package com.gallary.gallaryV1.model;

import java.time.LocalDateTime;
import java.util.List;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


@Schema(description = "Uploaded file data")
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class FileDetails {
	
	@Schema(example = "1")
    @Id
    @GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY)
    private int id;
	
	@Schema(example = "filename.jpg")
    private String fileName;
	
	@Schema(example = "D:/uploads/filename.jpg")
    private String filePath;
	
	@Schema(example = "File details generated by NLP Model")
    private String description;
	
	@Schema($comment  = "Tags to categories files.")
    @ElementCollection
    @CollectionTable(
    		name = "file_tags",
    		joinColumns = @JoinColumn(name = "file_id")
    )
	@Column(name = "tag")
	private List<String> tags;
	
	@Schema($comment = "Id of uploader")
    private int userId;

	@Schema($comment = "Time of upload of file")
    private LocalDateTime uploadTime;


}
